name: flutter_platter
description: A new Flutter application.

dependencies:
#  flutter:
#    sdk: flutter

  flutter_web: any

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.5.5+1

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  flutter_web_test: any
  build_runner: ^1.2.2
  build_web_compilers: ^1.1.0
  test: ^1.3.4

#flutter:
#
#  uses-material-design: true
#
#  assets:
#    - images/chicken.png
#    - images/pork.png
#    - images/taco_salad.png
#    - images/veg.svg

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
